// <auto-generated />
using System;
using ControleMinutas.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleMinutas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ControleMinutas.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EditadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxaAbastecimento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxaTroca")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("EditadoEm");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("ControleMinutas.Entities.Minuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EditadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrabalhoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("Data");

                    b.HasIndex("EditadoEm");

                    b.HasIndex("Status");

                    b.HasIndex("TrabalhoId");

                    b.ToTable("Minutas", (string)null);
                });

            modelBuilder.Entity("ControleMinutas.Entities.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EditadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("EditadoEm");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Terminais", (string)null);
                });

            modelBuilder.Entity("ControleMinutas.Entities.Trabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EditadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntregaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaidaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("EditadoEm");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EntregaId");

                    b.HasIndex("SaidaId");

                    b.ToTable("Trabalhos", (string)null);
                });

            modelBuilder.Entity("ControleMinutas.Entities.Minuta", b =>
                {
                    b.HasOne("ControleMinutas.Entities.Trabalho", "Trabalho")
                        .WithMany()
                        .HasForeignKey("TrabalhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ControleMinutas.Entities.ValueObjects.TrabalhoSnapshot", "DadosHistoricos", b1 =>
                        {
                            b1.Property<int>("MinutaId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("EmpresaNomeRegistrado")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Empresa");

                            b1.Property<decimal>("TaxaAbastecimentoAplicada")
                                .HasColumnType("TEXT")
                                .HasColumnName("TaxaAbastecimento");

                            b1.Property<decimal>("TaxaTrocaAplicada")
                                .HasColumnType("TEXT")
                                .HasColumnName("TaxaTroca");

                            b1.Property<string>("TerminalEntregaRegistrado")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Entrega");

                            b1.Property<string>("TerminalSaidaRegistrado")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Saida");

                            b1.Property<decimal>("ValorTrabalhoAplicado")
                                .HasColumnType("TEXT")
                                .HasColumnName("Valor");

                            b1.HasKey("MinutaId");

                            b1.ToTable("Minutas");

                            b1.WithOwner()
                                .HasForeignKey("MinutaId");
                        });

                    b.Navigation("DadosHistoricos")
                        .IsRequired();

                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("ControleMinutas.Entities.Trabalho", b =>
                {
                    b.HasOne("ControleMinutas.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleMinutas.Entities.Terminal", "Entrega")
                        .WithMany()
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleMinutas.Entities.Terminal", "Saida")
                        .WithMany()
                        .HasForeignKey("SaidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Entrega");

                    b.Navigation("Saida");
                });
#pragma warning restore 612, 618
        }
    }
}
